language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

before_install:
    - composer self-update

install:
    - composer install
    - npm install -g grunt-cli
    - npm install

script: grunt test

notifications:
    hipchat:
        rooms:
            secure: gIz9J1BNyH7P8O3d9Ey9PG6xU+hHydplXF+hm8ypuNOYjSL/U5VmTZLk3T5xyZzf9IGk039PDTEidngUOsGuosr6rvyjB11VpaDH+D/FRHDbkxw7+w/LTxZwGj84ntBqFSNYcoqJ31GPbBs+p+f1C4xC4XbFNrvkMMzgENXzc+s=
